"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const almacen_1 = __importDefault(require("./almacen"));
const almacenNumeros = new almacen_1.default();
almacenNumeros.toAddElement(7);
almacenNumeros.toAddElement(88);
almacenNumeros.toListElement();
console.log("Elemento en la posición 1:", almacenNumeros.toGetElement(0));
console.log("Elemento en la posición 2:", almacenNumeros.toGetElement(1));
const almacenCoches = new almacen_1.default();
almacenCoches.toAddElement("Renault");
almacenCoches.toAddElement("Skoda");
almacenCoches.toListElement();
console.log("Elemento en la posición 1:", almacenCoches.toGetElement(0));
console.log("Elemento en la posición 2:", almacenCoches.toGetElement(1));
const almacenAlumnos = new almacen_1.default();
almacenAlumnos.toAddElement({ nombre: "Jose", edad: 16 });
almacenAlumnos.toAddElement({ nombre: "Marta", edad: 31 });
almacenAlumnos.toListElement();
console.log("Elemento en la posición 1:", almacenAlumnos.toGetElement(0));
console.log("Elemento en la posición 2:", almacenAlumnos.toGetElement(1));
